# Generated by Django 2.2 on 2019-04-30 09:24

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20190402_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prepayment',
            field=django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True),
        ),
    ]
